print('hello, world!')
print('what is your name? ')
myname = input()
print('It is good to meet with you, ' + myname)
print('the length of your name is: '+ str(len(myname)))
print(len(myname))
print('what is your age?')
myage = input()
print("your age will be " + str(int(myage) + 1 ) + ' after a year.')
